---
  - name: Chown and Chmod on directory
    file:
      dest: "{{ knox.path }}/"
      owner: "{{ knox.ta }}"
      group: "{{ knox.ta }}"
      recurse: yes

  - name: Restart Knox.service
    systemd:
      name: knox.service
      state: restarted
      enabled: true
    ignore_errors: true

  - name: Reload daemon
    systemd:
      daemon_reload: true